# Default values for plugin-center.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scmmanager/plugin-center
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: plugin-center.scm-manager.org
      paths:
        - /

  tls: 
    - secretName: plugin-center-tls
      hosts:
        - plugin-center.scm-manager.org

resources:
  limits:
    memory: 16Mi
  requests:
    cpu: 100m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}
